'2016-10-19 20:15':
    id: 84857
    special:
    category: 'movie'

'2016-11-02 20:15':
    id: 773
    special:
    category: 'movie'

'2016-11-16 20:15':
    id: 116745
    special:
    category: 'movie'

'2016-11-30 20:15':
    id: 11083
    special:
    category: 'movie'

'2016-12-14 20:15':
    id: 392
    special:
    category: 'movie'

'2016-12-28 20:15':
    id: 878
    special:
    category: 'movie'

'2017-01-11 20:15':
    id: 100
    special:
    category: 'movie'

'2017-01-25 20:15':
    id: 374475
    special:
    category: 'movie'

'2017-02-08 20:15':
    id: 264660
    special:
    category: 'movie'

'2017-02-22 20:15':
    id: 10162
    special:
    category: 'movie'

'2017-03-08 20:15':
    id: 4538
    special:
    category: 'movie'

'2017-03-22 20:15':
    id: 265195
    special:
    category: 'movie'

'2017-04-05 20:15':
    id: 10315
    special:
    category: 'movie'

'2017-04-19 20:15':
    id: 583
    special:
    category: 'movie'

'2017-05-03 20:15':
    id: 464
    special:
    category: 'movie'

'2017-05-17 20:15':
    id: 169444
    special:
    category: 'movie'

'2017-05-31 20:15':
    id: 63849
    special:
    category: 'movie'

'2017-06-14 20:15':
    id: 38
    special:
    category: 'movie'

'2017-06-28 20:15':
    id: 782
    special:
    category: 'movie'

'2017-07-12 20:15':
    id: 361403
    special:
    category: 'movie'

'2017-07-26 20:15':
    id: 1262
    special:
    category: 'movie'

'2017-08-04 22:00':
    id: 11227
    special: true
    category: 'movie'

'2017-08-09 20:15':
    id: 334533
    special:
    category: 'movie'

'2017-08-23 20:15':
    id: 300
    special:
    category: 'movie'

'2017-09-06 20:15':
    id: 186
    special:
    category: 'movie'

'2017-09-20 20:15':
    id: 1599
    special:
    category: 'movie'

'2017-10-04 20:15':
    id: 582
    special:
    category: 'movie'

'2017-10-11 20:15':
    id: 33605
    special:
    category: 'documentation'

'2017-10-18 20:15':
    id: 1023
    special:
    category: 'movie'

'2017-10-25 20:15':
    id: 226109
    special:
    category: 'documentation'

'2017-11-01 20:15':
    id: 278
    special:
    category: 'movie'

'2017-11-15 20:15':
    id: 401441
    special:
    category: 'documentation'

'2017-11-22 20:15':
    id: 9459
    special:
    category: 'documentation'

'2017-12-06 20:15':
    id: 9459
    special:
    category: 'documentation'

'2017-12-10 16:00':
    id: 70232
    special: true
    category: 'movie'

'2017-12-13 20:15':
    id: 381284
    special:
    category: 'movie'

'2017-12-20 20:15':
    id: 371492
    special:
    category: 'documentation'

'2017-12-27 20:15':
    id: 85350
    special:
    category: 'movie'

'2018-01-03 16:00':
    id: 335797
    special: true
    category: 'movie'

'2018-01-03 20:15':
    id: 22074
    special:
    category: 'documentation'

'2018-01-10 20:15':
    id: 404
    special:
    category: 'movie'

'2018-01-24 20:15':
    id: 6947
    special:
    category: 'movie'

'2018-01-31 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'Kabarett-Mittwoch'
        image: 'Lisa-Feller.jpg'
        tagline: ''
        overview: 'Diesen Mittwoch gibt es wieder eine Attacke auf unsere Lachmuskeln. Denn dieser Mittwoch ist Kabarett-Mittwoch!'

'2018-02-07 20:15':
    id: 27936
    special:
    category: 'movie'

'2018-02-14 20:15':
    id: 52254
    special:
    category: 'documentation'

'2018-02-21 20:15':
    id: 4816
    special:
    category: 'movie'

'2018-02-28 20:15':
    id: 504161
    special:
    category: 'documentation'

'2018-03-07 20:15':
    id: 340
    special:
    category: 'movie'

'2018-03-14 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'Ausgefallen'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-03-21 20:15':
    id: 1885
    special:
    category: 'movie'

'2018-03-28 20:15':
    id: 99882
    special:
    category: 'documentation'

'2018-04-04 20:15':
    id: 6007
    special:
    category: 'movie'

'2018-04-11 20:15':
    id: 124075
    special:
    category: 'documentation'

'2018-04-18 20:15':
    id: 31175
    special:
    category: 'movie'

'2018-04-25 20:15':
    id: 265297
    special:
    category: 'documentation'

'2018-05-02 20:15':
    id: 234200
    special:
    category: 'movie'

'2018-05-09 20:15':
    id: 267379
    special:
    category: 'documentation'

'2018-05-16 20:15':
    id: 10849
    special:
    category: 'movie'

'2018-05-23 20:15':
    id: 347214
    special:
    category: 'documentation'

'2018-05-30 20:15':
    id: 274415
    special:
    category: 'movie'

'2018-06-06 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'Qualityland'
        image: 'qualityland.jpg'
        tagline: ''
        overview: ''

'2018-06-13 20:15':
    id: 1611
    special:
    category: 'movie'

'2018-06-20 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-06-27 20:15':
    id: 0
    special:
    category: 'movie'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-07-04 20:15':
    id: 103773
    special:
    category: 'documentation'

'2018-07-11 20:15':
    id: 0
    special:
    category: 'movie'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-07-18 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-09-01 20:15':
    id: 120467
    special: true
    category: 'movie'

'2018-09-05 20:15':
    id: 134
    special:
    category: 'movie'

'2018-09-19 20:15':
    id: 492
    special:
    category: 'movie'

'2018-09-26 20:15':
    id: 511736
    special:
    category: 'documentation'

'2018-10-03 20:15':
    id: 338
    special:
    category: 'movie'

'2018-10-17 20:15':
    id: 8265
    special:
    category: 'movie'

'2018-10-24 20:15':
    id: 254214
    special:
    category: 'documentation'

'2018-10-31 20:15':
    id: 254375
    special:
    category: 'movie'

'2018-11-14 20:15':
    id: 637
    special:
    category: 'movie'

'2018-11-28 20:15':
    id: 71
    special:
    category: 'movie'

'2018-12-02 15:00':
    id: 12097
    special: true
    category: 'movie'

'2018-12-05 20:15':
    id: 555912
    special:
    category: 'documentation'

'2018-12-12 20:15':
    id: 562
    special:
    category: 'movie'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-12-19 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'fällt aus'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2018-12-26 20:15':
    id: 0
    special:
    category: 'movie'
    custom:
        title: 'tbd'
        image: 'dummy.png'
        tagline: ''
        overview: ''

'2019-01-02 20:15':
    id: 453386
    special:
    category: 'documentation'

'2019-01-09 20:15':
    id: 487558
    special:
    category: 'movie'

'2019-01-16 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'Zartbitter - Präventionstheater gegen sexuellen Missbrauch'
        image: 'zartbitter.jpg'
        tagline: 'Zartbitter-Präventionstheaterstück für Mütter, Väter und pädagogische Fachkräfte'
        link: 'www.zartbitter.de/gegen_sexuellen_missbrauch/Praeventionstheater/203_bei_uns_doch_nicht.php'

'2019-01-23 20:15':
    id: 436167
    special:
    category: 'movie'

'2019-01-30 20:15':
    id: 0
    special:
    category: 'documentation'
    custom:
        title: 'No more Boys and Girls'
        image: 'gender.jpg'
        tagline: 'Alles Gender, oder was?'
        overview: 'In einem Sozialexperiment zeigt die Moderatorin Collien Ulmen-Fernandes, wie konservativ und klassisch selbst bei heute 7-Jährigen die Rollenbilder von Frau und Mann sind und woher das kommt.'
        link: 'www.zdf.de/dokumentation/no-more-boys-and-girls/berufe-100.html'
